version: '3.8'
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    container_name: admin-pos-service-go
    build: .
    env_file:
      - .env
    ports:
      - 8881:8881
    networks:
      - digylabs-admin-pos-service
  ### ========================
  ### VOLUMES PERSISTENT DATA
  ### ========================
# volumes:
#   pg-data:
  ### ===================================
  ### NETWORKS GROUP FOR ONE SAME SERVICE
  ### ===================================
networks:
  digylabs-admin-pos-service:
